### ISSUE TITLE
Openapi 3.1 support in the model

### ISSUE THREAD

**Issue by hamnis** [softwaremill/tapir#1147]
https://github.com/OAI/OpenAPI-Specification/releases/tag/3.1.0

**Comment by adamw** [comment]
Related: https://github.com/swagger-api/swagger-ui/issues/5891

**Comment by rojekp** [comment]
So far, I added new fields for 3.1.0 OpenAPI model.

**Comment by adamw** [comment]
We have to wait until Swagger supports 3.1

**Comment by yoohaemin** [comment]
Is it a possibility that tapir maintains support for both 3.0.x and 3.1 for some time? I understand Swagger is the immediate blocker, but even after that there might be other tooling that may still be stuck on 3.0.x 🤔 

I'm a bit careful with this request though, because it will be a burden for the maintainers of this repository.

**Comment by adamw** [comment]
@yoohaemin I think we'll rather switch to 3.1 at some point. Maintaining two branches might be problematic. But not impossible - would be a matter of creating two separate documentation interpreters.

**Comment by adamw** [comment]
But please vote on the issue (with 👍 ) so that we can see how popular it is :)

**Comment by LeifW** [comment]
We've switched from swagger-ui to stoplight elements, as it gives a much nicer view of our API, and stoplight elements supports openapi 3.1
