### ISSUE TITLE
Feature Request: ability to enable and disable endpoints via feature flag configuration

### ISSUE THREAD

**Issue by ithinkicancode** [softwaremill/tapir#1264]
Inspired by this Java project: https://github.com/facet-tech/agent-java

Feature flag management/capability is a common way in software development to enable and disable certain product features for various purposes (A/B testing, demos, perhaps even licensing, etc).

It will be great if Tapir has this capability built-in. Either via some configuration mechanism or, even better, some form of realtime toggling without modifying or restarting server app (might require a java agent).

Adam mentioned on gitter that this can be implemented as interceptor.

**Comment by tg44** [comment]
For akka-http and paid features (with signed-keys as realtime config) we do the following;
 - all of our API classes has a `def endpoints(implicit enabledFeatures: Seq[String]): List[ServerEndpoint[_, _, _, AkkaStreams with WebSockets, Future]]` function so they can compose the endpoints based on their availability
 - we have a cache with the composed routes
 - we use a selfgrown lowlevel akka routing which can read the cache

Pros;
 - it works without a server restart
 - cache reset won't affect already running connections
 - when sb set a new key, or a key expires we just reset the cache, not a big deal
 - the user only sees the available/paid routes in the documentation
 - the needed features in the same file as the routes

Cons;
 - not "really" real-time, resetting a cache is not what I would call realtime
 - it had bugs early on could be some still unknown
 - it could have performance decrease (but not really sure)
 - can't handle A/B testing or per user testing
 - a bit rigid for my taste :)

### Codes;
An API (with helpers);
```scala
def endpoints(implicit enabledFeatures: Seq[String]): List[ServerEndpoint[_, _, _, AkkaStreams with WebSockets, Future]] =
    uploadData :: onlyIfFeatureOn(Features.additionalData) {
      List(
        downloadData,
      )
    }
```
Building all the routes;
```scala
private val endpointsCache = new SingleCache[Route](() => {
    import akka.http.scaladsl.server.Directives._
    for {
      ef <- services.featureService.getAllEnabledFeatures()
    } yield {
      val endpoints = allApis.flatMap(_.endpoints(ef))
      logger.info(s"Endpoint refresh! Currently available tapir endpoints; ${endpoints.size}")
      cors(corsSettings) {
        tapirToRoutes(endpoints) ~
          asyncApiRoute(endpoints) ~
          swaggerRoute(endpoints)
      }
    }
  })
```
Cache with mutable code, but it is safe (caches futures, returns the same panding/finished future to multiple callers);
```scala
class SingleCache[T](f: () => Future[T])(implicit executionContext: ExecutionContext) {
  private var c: Option[Future[T]] = None

  def get: Future[T] = c.getOrElse(runGet)
  def reset(): Unit = { c = None }

  private def runGet = {
    val k = f()
    c = Option(k)
    k.onComplete(removeIfFailed(k))
    k
  }

  private def removeIfFailed(k: Future[T])(p: Try[T]): Unit =
    p match {
      case Success(x) => ()
      case Failure(_) =>
        c.foreach { fut =>
          if(fut == k) c = None
        }
    }
}
```

Starting the akka server (this is the black-magic part);
```scala
def startWebserver(routeGen: () => Future[Route])(
      implicit actorSystem: ActorSystem,
      materializer: Materializer,
      executionContext: ExecutionContext,
  ): Future[Http.ServerBinding] = {
    import JsonBasedRejectionHandler._
    val settings = ServerSettings(actorSystem)
    val (bind, done) = Http()
      .newServerAt("0.0.0.0", 9000)
      .connectionSource()
      .mapAsyncUnordered(settings.maxConnections) { in =>
        in.handleWith(
          Flow[HttpRequest]
            .mapAsync(1)(in => routeGen().flatMap(_(in)))
            .watchTermination()(Keep.right)
        ).recover {
          case ex =>
            logger.info(s"Routing error!", ex)
            Done
        }
      }
      .toMat(Sink.ignore)(Keep.both)
      .run()

    done.onComplete {
      case Success(_)  => logger.info(s"Web server STOPPED")
      case Failure(ex) => logger.error(s"Web server STOPPED with an error!", ex)
    }

    bind.map { binding =>
      logger.info(s"Web server started on 0.0.0.0:9000")
      setupShutdownHook(binding)
      binding
    }
  }
```

**Comment by adamw** [comment]
How about the following:

* we add a free-form attribute map to endpoints, which would allow adding arbitrary meta-data for an endpoint (similar to sttp-client [tagging](https://sttp.softwaremill.com/en/latest/backends/wrappers/custom.html#request-tagging), but here "tag" is already taken and has a different - OpenAPI - meaning). This allows specifying which endpoints correspond to which features, or what kind of roles they require. We could imagine some kind of typed map with typed keyes.
* we add a similar attribute map to `ServerRequest`. When a request arrives, a `RequestInterceptor` can perform the request-specific calculation to determine the request's attributes which will then be used to determine if an endpoint is enabled (this is more of an optimization, not to perform this work each time)
* to capture the moment before decoding a request given a specific endpoint, we'd have to extend the `EndpointHandler` so that the `decode` function is called at the appropriate time in the `ServerInterceptor`. This would give us the opportunity to filter out any endpoints that don't match the attributes computed before. Such an interceptor could either be added globally, or on-demand using the previously called `RequestInterceptor`, which would nicely encapsulate the whole functionality in a single class.

Here's the possible shape of the extended `EndpointIntreceptor`:

```scala
sealed trait ServerDecodeResult
object ServerDecodeResult {
  case class Success[I](i: I) extends ServerDecodeResult
  case class Failure(input: EndpointInput[_], failure: DecodeResult.Failure) extends ServerDecodeResult
}

trait EndpointHandler[F[_], B] {
  def decode(ServerRequest, ServerEndpoint) => F[ServerDecodeResult]
  def onDecodeResult(ServerRequest, ServerEndpoint, ServerDecodeResult) => F[Option[ServerResponse[B]]]
}

trait EndpointInterceptor[F[_], B] extends Interceptor[F, B] {
  def apply(Responder[F, B], nested: EndpointHandler[F, B]) => EndpointHandler[F, B]
}
```
