### ISSUE TITLE
[BUG] Either type in the model

### ISSUE THREAD

**Issue by arvkonstantin** [softwaremill/tapir#1300]
Tapir version: 0.18.0-M15

Scala version: 2.13.6

**Describe the bug**

I'm having trouble generating the api when the Either type is present in the model. 
```
{
  "data": {
    "value": "string"
  }
}
```
The data field is of type Either[A, B]. If you click "Try it out" in the Swagger UI, the example made by Swagger does not work. It is necessary to add 
```
{
  "data": {
    "Left": {
      "value": "string"
    }
  }
}
```
then everything will work, but it is not described in the yaml schema.

**How to reproduce?**

1) Run [this project](https://github.com/arvkonstantin/tapirBug). 
2) Open http://localhost:8081/api/
3) Click "Try it out"
4) Click "Execute"
You will get "Error: Bad Request"
Wrap the value in "Left"
```
"Left": {
      "value": "string"
}
```
This will work, but there is no information about "Left" in the yaml schema.

**Comment by adamw** [comment]
Given `case class TestCommand(data: Option[Either[String, Int]])`, `TestCommand(Left("test"))` can be serialised to json in three ways:

```scala
// 1
{ 
  "data": "test" 
} 

// 2
{ 
  "data": {
    "value": "test" 
  }
} 

// 3
{ 
  "data": {
    "Left": {
      "value": "test" 
    }
  }
} 
```

The question is, which one you want :). When it comes to tapir, there are two components that you have to define:

(a) the circe encoder/decoder, which is used to serialise to/from json
(b) the schema, which is used to generate documentation

The problems come from the fact that by default, for (a) - circe decoding - `// 3` is assumed the data format, and for (b) - tapir schemas - `// 2`. Hence the discrepancy.

This stems from the way sealed traits are handled - and `Either` is nothing else than a sealed trait with `Left` & `Right` cases. Tapir schemas just takes the cases and lists them using `oneOf` (see [the docs](https://tapir.softwaremill.com/en/latest/endpoint/schemas.html#sealed-traits-coproducts)). On the other hand, circe uses a different default, where the cases are tagged with the class name, so that they can be deserialised later.

As an intermediate solution, you can override the default schemas/codecs that are used so that they match your needs. However, some things are missing in tapir to be able to achieve this. For example, `// 1` can be represented using circe as follows:

```scala
// for circe, see https://github.com/circe/circe/issues/672
implicit def eitherDecoder[A, B](implicit a: Decoder[A], b: Decoder[B]): Decoder[Either[A, B]] = {
  val left: Decoder[Either[A, B]] = a.map(Left.apply)
  val right: Decoder[Either[A, B]] = b.map(Right.apply)
  left.or(right)
}
```

But there's no way in tapir to represent a coproduct (one-of schema) using primitive types (the children have to be objects currently). So that's one thing to improve.

The second - should there be a default `Either` codec in tapir? Probably yes, once we have implemented the above.
