### ISSUE TITLE
Investigate AWS CDK

### ISSUE THREAD

**Issue by adamw** [softwaremill/tapir#1441]
Currently we've got a module generating AWS SAM templates, but maybe we could generate some kind of a [CDK](https://docs.aws.amazon.com/cdk/latest/guide/home.html) library as well? So that the translated tapir endpoint descriptions can be used in a cdk-managed serverless app.

**Comment by NickBurkard** [comment]
I've been maintaining a library for [Scala CDK bindings](https://github.com/NickBurkard/aws-cdk-scala), it generates Scala code to wrap the underlying Java CDK & provide a safer API (`Option` instead of `null`, Scala collections, etc.). Not sure how relevant it is to tapir's CDK use cases, but figured it's worth mentioning. 😄

**Comment by adamw** [comment]
This is available for some time now: https://tapir.softwaremill.com/en/latest/server/aws.html
