### ISSUE TITLE
Investigate exposing endpoints using gRPC

### ISSUE THREAD

**Issue by adamw** [softwaremill/tapir#1489]
I think it's doable, but the question is would people want to actually use this kind of functionality :)

Maybe we could generate proto files from endpoint descriptions? Would that be useful at tall, given that usually generation is done the other way round? What kind of endpoint inputs/output could we support, and what to do if a given input/output cannot be used in a gRPC endpoint?

**Comment by WayneWang12** [comment]
A better way might be generate tapir endpoints from proto files.

**Comment by borissmidt** [comment]
There is [mu-scala](https://github.com/higherkindness/mu-scala) that covers this, But i think you will need a limited syntax for this because most rest api's are not valid grpc apis.


I really see added value in the ability to describe the MetaData grpc request like authentication/tracing etc. 
But you would loose it when you go back to a protobuf description.
