### ISSUE TITLE
Can toDirective be re-instated?

### ISSUE THREAD

**Issue by izzyreal** [softwaremill/tapir#1500]
Our project currently relies heavily on `toDirective`, which was removed in `tapir` 0.18. Would it be possible to get it back?

In the meantime we will investigate using the new interceptors and `tapir` DSL like `out`, `header` and `serverLogic`, but for now it would be great if we can get some breathing room to keep `tapir` up to date.

**Comment by adamw** [comment]
Well, if it would be possible, I wouldn't remove it :) The problem is that in `toDirective`, parsing the input & encoding the output is split into two parts. With the single, centralised `ServerInterpreter` (which is shared among all interpreters), there's no way for the interpreter to interrupt the process in the middle. It would mean writing a special akka version of `ServerInterpreter`, which would split the processing into two parts, repeating the interceptor logic etc.

**Comment by izzyreal** [comment]
Alright thanks, we'll try to factor out our use of `toDirective`.

**Comment by adamw** [comment]
If you'd encounter any roadblocks along the way, let me know, maybe there's a solution using the existing functionality, or maybe some functionality is missing :)

**Comment by izzyreal** [comment]
Thanks @adamw, we'll keep you posted on roadblocks.
