### ISSUE TITLE
Implicit Rejection/Exception handlers support (akka http)

### ISSUE THREAD

**Issue by korgillya** [softwaremill/tapir#169]
Is it possible to use our custom Exception/Rejection handlers in generated routes?

**Comment by adamw** [comment]
Yes, you should be able to use exception handlers as always - just use them as with any other route.

Rejections will be harder ... tapir has its own decoding/rejection mechanism (see https://tapir-scala.readthedocs.io/en/latest/server/errors.html#handling-decode-failures), so you might have to move some of that logic there.

**Comment by kromuch** [comment]
@adamw, please check this PR: https://github.com/softwaremill/tapir/pull/172, it might be useful in porting `RejectionHandler`s to Tapir without loss of compatibility with old versions of Tapir and without loss of functionality in comparison with Akka's `RejectionHandler`.

**Comment by adamw** [comment]
@kromuch hmm, I think I would need some examples to see what you mean. You mention two things - one is porting `RejectionHandler`s, and the other that some functionality is missing from tapir comparing to `RejectionHandler`s?

**Comment by 0lejk4** [comment]
As for now, there is a way to handle all of the mentioned here, tapir got DecodeFailureHandler that gives the ability to handle all rejections like in RejectionHandler. And like you said there is a way to use existing Exception handlers. This issue was created by my coworkers because we made a poor investigation of what tapir can do. We solved all our problems with tapir and are pretty happy with using it. This issue can be closed, thank you for your work :smile:

**Comment by adamw** [comment]
@0lejk4 no worries and thanks for the info. It's quite probably that the docs are unclear an insufficient - please let me know of any such instances! I've already noted that the exception handling section probably needs a re-work some point in the near future :)
