### ISSUE TITLE
Adding examples to query fields breaks yaml

### ISSUE THREAD

**Issue by adamw** [softwaremill/tapir#1801]
See https://gitter.im/softwaremill/tapir?at=61e1664fbfe2f54b2e1a2d0d

**Comment by kubinio123** [comment]
So if we define a single example it should be mapped to OpenAPI [example](https://spec.openapis.org/oas/v3.1.0#:~:text=for%20the%20parameter.-,example,-Any) field however it does not allow summary and name - only list of examples in OpenAPI allow that parameters (see Example Object). So when name or summary is provided we should map it to _examples_ list instead of single example
