### ISSUE TITLE
[Feature] add description to security scheme model

### ISSUE THREAD

**Issue by kubinio123** [softwaremill/tapir#1839]
Currently we don't support description on security schemes (`EndpointIO.Auth`). We could also see if we can support some other fields from ones listed in ref [here](https://spec.openapis.org/oas/v3.1.0#security-scheme-object). 
Finally we should be able to say `.in(auth.bearer[Authorization]().description(...)` and also be able to do the same with endpoint IO annotations.

**Comment by adamw** [comment]
The problem is that auth wraps a `Single` which can also be a `Pair`. Can't you set a description on the nested input? 

Looking at the code, this can be done for `auth.apiKey`, but not for `auth.basic`. Here we would need to add a transformation function which would have the option to customise the nested header input. What do you think?

Where's the description example in the spec, I can't find it (the link just goes to the top of the page)

**Comment by kubinio123** [comment]
I updated the link. Adding such function sounds good, then we have only to adjusting mapping to `SecurityScheme`

**Comment by adamw** [comment]
Ah I see ... well maybe we should indeed add a `description` to `Auth` then
