### ISSUE TITLE
[IMPROVEMENT] Add security output to DecodeFailureContext 

### ISSUE THREAD

**Issue by trackiss** [softwaremill/tapir#1975]
It would be nice if DecodeFailureContext has a parameter of the optional security output (`Option[PRINCIPAL]`).
like this:

```diff
  case class DecodeFailureContext(
      failingInput: EndpointInput[_],
      failure: DecodeResult.Failure,
+     securityLogicResult: Option[_]
      endpoint: AnyEndpoint,
      request: ServerRequest
  )
```

For example, this is ideal for handling the case where "the decoding of the security input succeeded and the security logic succeeded, but the decoding of the other inputs failed".

**Comment by trackiss** [comment]
It would also be better if the optional security output could be used within `ServerLog.exception`.

**Comment by adamw** [comment]
@trackiss turns out that unfortunately most of the time the security logic result or even the security input (decoded) won't be available. That's because we short-circuit the decoding of an endpoint's inputs as soon as possible. In the beginning of the process, both the security & regular **basic** inputs are decoded (without the body), and at that point most failure occur. So if a basic input from the "regular" section fails to decode (such as a path fragment), the security logic won't be run, and even the security input won't be fully created.

I've added more context to the exception-handling logic, though.
