### ISSUE TITLE
[FEATURE] Support `oneOfBody` with `streamBody`

### ISSUE THREAD

**Issue by gaeljw** [softwaremill/tapir#2039]
I would like to be able to define an endpoint that returns a streaming body of the same type with different format (JSON and XML for instance).

If I was not having a streaming body I would use `oneOfBody(jsonBody[T], xmlBody[T])` but `oneOfBody` doesn't support `streamBody` as inputs.

I'm not sure if this is a missing feature or if there is a deeper reasoning behind not having this possibility.

Ideally I would like to be able to define something like this:
```scala
private val jsonOutput: StreamBody[Source[ByteString, Any], Source[ByteString, Any], AkkaStreams] =
  streamBody(AkkaStreams)(Schema.derived[T].asIterable, CodecFormat.Json())

private val xmlOutput: StreamBody[Source[ByteString, Any], Source[ByteString, Any], AkkaStreams] =
  streamBody(AkkaStreams)(Schema.derived[T].asIterable, CodecFormat.Xml())

val endpoint = ...
  .out(oneOfBody(jsonOutput, xmlOutput))
```

Relates to https://github.com/softwaremill/tapir/issues/690

**Comment by paulpdaniels** [comment]
Excellent I don't need to create my own issue, can just piggy back on this one. To give another example of where this is needed. I have a scenario where I need to send _either_ a customJson payload or a multipart streamed body depending on the response type.

```scala
private val singleResponseOutput: StreamBody[Source[ByteString, Any], Source[ByteString, Any], AkkaStreams] =
  streamBody(AkkaStreams)(GraphQLResponse.schema, CodecFormat.Json())

private val multiResponseOutput: StreamBody[Source[ByteString, Any], Source[ByteString, Any], AkkaStreams] =
  streamBody(AkkaStreams)(DeferredGraphQLResponse.schema, CodecFormat.Json())

val endpoint = 
  partial.out(oneOf(
    oneOfVariantStreaming(singleResponseOutput),
   oneOfVariantStreaming(singleResponseOutput)
  ))
```

In our case I don't think `oneOfBody` would be sufficient, it needs the whole `oneOf` machinery because we will have different headers as well.

**Comment by adamw** [comment]
This turns out to be quite tricky to implement. The problem is that the streaming inputs/outputs should influence the last type parameter of `Endpoint`, specifying the endpoint's requirements (such as streaming).

Currently this is implemented so that `EndpointInput` and `EndpointOutput` are kept simpler, without the additional type parameter - they are always assumed to have **no** additional requirements. `streamBody` returns value of a type, for which an overloaded variant of the `.in` and `.out` methods exist. These overloaded variants change the 4th type parameter so that the streaming information ends up in the `Endpoint` type.

Now `oneOf` is a normal output, meaning that it does not carry (or propagate) any streaming requirements. There's a (hidden) assumption that any outputs used there don't have any additional requirements when it comes to interpreters. How to fix this? There's a couple of options:

1. add `R` as a second type parameter to `EndpointInput`. This would allow propagating the streaming requirements, but would also be very disruptive as it would complicate the type signatures of all of the inputs and outputs; 99% of the time the value of this type parameter would be `Any`.
2. create an "escape hatch" allowing lifting a streaming body to an `EndpointInput`/`EndpointOutput`, "forgetting" the streaming requirements and allowing such bodies to be using in `oneOf` (this could be called `.toInput` or `.toOutput`).  The downside is of course worse type-safety - it would be possible to construct an endpoint which uses a streaming body, and interpret it using a server interpreter which doesn't support these streams. Such hidden requirements wouldn't also propagate to the type of the endpoint (unless specified manually). However, this is made somewhat unlikely as if a `Streams` implementation is on the classpath, it's probably brought in by the corresponding interpreter. Still, care would need to be taken by the developer
3. create a dedicated `oneOfStream` type which would (similarly to stream bodies) have dedicated overloads for `.in` and `.out`. However, in the variants the streaming bodies would need to be specified separately, which again creates the problem of discriminating which variant to use. So we would need to capture 3 things: the stream body (if any), the rest of the one-of-variant's-output, and a mapping to a high-level type which is then used for discriminating when encoding the response (choosing the right variant). This could end up being quite complex.

What do you think? :)

**Comment by gaeljw** [comment]
Interesting.

IMHO option 1 is not worth it.

Then, option 2 doesn't feel that "risky" to me because people are expected to test their endpoint and would notice right away that something is not working but it's a shame to loose the type safety that Tapir brings.

Finally, option 3 would have been the one I would have tried If I had started a PR. I'm not sure I completely understand the complexity here: it comes from the fact that there might be output variants with stream bodies and output variants without stream bodies? Would it make sense / simplify things to assume that all output variants (not considering error output) either use streaming or neither do?

**Comment by adamw** [comment]
Re: option 3 - yes, the fact that stream bodies might only be present in some of the variants is one of the sources of complexity. However, the main problem is that the stream body must be specified separately from the other outputs (to capture the right streaming requirement). And so a variant ends up as a tuple `(Stream, OtherOutputs)`. So if you want to have a hierarchy of types representing various variants, you'll also need a `Mapping` between that tuple and the high-level types. Then when encoding the response, you can choose the variant to use based on the specific implementation passed.

That said, I'm leaning towards 2. as well ;)

**Comment by gaeljw** [comment]
With option 2 I have a doubt: would the user have to specify the `R` type as it would not be propagated when doing `.out(oneOfBody(jsonOutput, xmlOutput))`? Or you mean "internally" we will loose the type as it's already happening with the `StreamBodyWrapper`?

I don't know/understand enough how this piece of the lib work to give a definitive answer but option 2 sounds acceptable :)

**Comment by adamw** [comment]
Well you could end up with an `Endpoint[..., Any]` (that is with `R == Any`), but which uses a `streamBody` internally. As long as you use an interpreter that supports these streams, things will work fine. You only loose the static guarantees that you won't use an incorrect endpoint with an incorrect interpreter.

Yes, internally we always use the type via `StreamBodyWrapper`, but so far this wasn't visible to the user.

**Comment by adamw** [comment]
In the end I went with 2. - see the PR for details. One limitation is that mixed streaming/non-streaming variants in `oneOf` won't work with client interpreters.
