### ISSUE TITLE
[BUG] Errors in serverSecurityLogic should take precedence over decoding errors

### ISSUE THREAD

**Issue by benjamingeer** [softwaremill/tapir#2268]
Tapir version: 1.0.1

Scala version: 2.13.8

**Describe the bug**

I have an endpoint with `serverSecurityLogic`, as well as a custom `DecodeFailureHandler` that returns `BadRequest` for invalid input. If the endpoint's `serverSecurityLogic` returns an error, and a decoding error also occurs when parsing the input parameters, the client receives the error from the `DecodeFailureHandler` instead of the error from the `serverSecurityLogic`.

This seems like a security bug to me: an endpoint should not reveal information about itself, e.g. via error messages concerning the syntax of its parameters, to clients that don't have permission to use it. If a client doesn't have permission to use the endpoint, I only want them to receive the error from `serverSecurityLogic`.

**How to reproduce?**

Here is a failing test that reproduces the problem:

```scala
package example

import akka.http.scaladsl.model.StatusCodes
import akka.http.scaladsl.testkit.ScalatestRouteTest
import org.scalatest.matchers.should.Matchers
import org.scalatest.wordspec.AnyWordSpec
import sttp.model.StatusCode
import sttp.tapir._
import sttp.tapir.model.UsernamePassword
import sttp.tapir.server.akkahttp.{ AkkaHttpServerInterpreter, AkkaHttpServerOptions }
import sttp.tapir.server.interceptor.DecodeFailureContext
import sttp.tapir.server.interceptor.decodefailure._
import sttp.tapir.server.model.ValuedEndpointOutput

import scala.concurrent.Future

class ServerSecurityLogicTest extends AnyWordSpec with ScalatestRouteTest with Matchers {
  type ErrorInfo = (StatusCode, String)

  def authLogic(usernamePassword: UsernamePassword): Future[Either[ErrorInfo, String]] =
    Future(Left((StatusCode.Unauthorized, "Unauthorized")))

  val echoEndpoint = endpoint
    .securityIn(auth.basic[UsernamePassword]())
    .errorOut(statusCode)
    .errorOut(plainBody[String])
    .serverSecurityLogic(authLogic)
    .in("example")
    .in(path[Int]("value"))
    .out(plainBody[String])
    .serverLogic { principal: String => value: Int =>
      Future.successful(Right(s"Value: $value"))
    }

  val decodeFailureHandler = new DecodeFailureHandler {
    override def apply(ctx: DecodeFailureContext): Option[ValuedEndpointOutput[_]] =
      ctx.failure match {
        case DecodeResult.Error(_, ex) =>
          Some(
            ValuedEndpointOutput(
              statusCode(StatusCode.BadRequest).and(plainBody[String]),
              ex.getMessage
            )
          )

        case _ => DefaultDecodeFailureHandler.default.apply(ctx)
      }
  }

  val serverOptions = AkkaHttpServerOptions.customiseInterceptors
    .decodeFailureHandler(decodeFailureHandler)
    .options

  val route = AkkaHttpServerInterpreter(serverOptions).toRoute(echoEndpoint)

  "The example route" should {
    "return Unauthorized if the client is not authenticated and submits a valid integer" in {
      Get("/example/5") ~> route ~> check {
        response.status shouldBe StatusCodes.Unauthorized
      }
    }

    "return Unauthorized if the client is not authenticated and submits an invalid integer" in {
      Get("/example/abc") ~> route ~> check {
        response.status shouldBe StatusCodes.Unauthorized
      }
    }
  }
}
```

**Additional information**

**Comment by adamw** [comment]
This is by design: first, the security & regular inputs are decoded, and only when the endpoint "matches" the request, the security logic is run. See [`ServerInterpreter`](https://github.com/softwaremill/tapir/blob/91a99234062a6f07f2ee672e77e8988433c158ee/server/core/src/main/scala/sttp/tapir/server/interpreter/ServerInterpreter.scala#L88-L105) for some more details.

The reason to do it this way is that often the security inputs contain only a part of e.g. the path. Then, multiple endpoints might match a request, and the security logic would be run needlessly multiple times. So we first pick "the" endpoint to try, and only if it matches, the logic is run.

To fix your problem, I don't think you'll manage to return descriptive error messages only if the security logic succeeds (as the ordering is hard-coded in `ServerInterpreter`), but there are some other things you can try. For example, [endpoints with authentication inputs can be hidden](https://tapir.softwaremill.com/en/latest/server/options.html#hiding-authenticated-endpoints). You can also write a custom `DecodeFailureHandler` which hides the error details if the failing input comes from the "regular" inputs, but exposes them if the input is part of the "security" inputs - see `EndpointInput.pathTo`. Maybe you could even run the security logic there, but that would be quite a hack ;)

Hope this helps :)
