### ISSUE TITLE
[BUG] errorOutVariant causes the server not to return any response

### ISSUE THREAD

**Issue by jwojnowski** [softwaremill/tapir#2434]
Tapir version: 1.1.0

Scala version: 2.13.8

ZIO version: 2.0.2

http4s version: 0.23.12

**Describe the bug**

Defining server endpoint's errors in two separate steps using `errorOut` and `errorOutVariant` causes the server not to return any response (request times out in the end) when the result is an error matched by `errorOutVariant`.

Unless I'm wrong in my understanding that:
```scala
endpoint
  .errorOut(oneOf(matcher1, matcher2))
```
should be equivalent to

```scala
endpoint
  .errorOut(oneOf(matcher1))
  .errorOutVariant(matcher2)
```

**How to reproduce?**

https://github.com/jwojnowski/tapir-erroroutvariant-bug-report-example

**Comment by adamw** [comment]
There are a couple of problems that lead to this behavior :)

First off, by default ZIO doesn't report exceptions, that cause a fiber to die. These can be logged by adding a logger, in the main class you can add:

```scala
  override val bootstrap: ZLayer[Any, Nothing, Unit] = zio.Runtime.addLogger(new ZLogger[String, Unit] {
    def apply(
        trace: Trace,
        fiberId: FiberId,
        logLevel: LogLevel,
        message: () => String,
        cause: Cause[Any],
        context: FiberRefs,
        spans: List[LogSpan],
        annotations: Map[String, String]
    ): Unit =
      println(s"LOG: $message, cause: ${cause.prettyPrint}")
  })
```

(or any other logger such as slf4j)

Second, I think it's a problem of zio-cats-interop module, but maybe you can verify this on Discord or create an issue there. With zio+http4s, the following just drops the connection:

```scala
import org.http4s.HttpRoutes
import org.http4s.blaze.server.BlazeServerBuilder
import zio.interop.catz._
import zio.{Scope, Task, ZIO, ZIOAppArgs}

object Main extends zio.ZIOAppDefault {
  override def run: ZIO[Any with ZIOAppArgs with Scope, Any, Any] = {
    val routes2 = HttpRoutes.of[Task] { case _ =>
      throw new IllegalArgumentException("boom")
    }

    BlazeServerBuilder[Task]
      .bindHttp(port = 8080, host = "0.0.0.0")
      .withHttpApp(routes2.orNotFound)
      .resource
      .toScopedZIO *> ZIO.never
  }
}
```

While the equivalent using cats-effect, returns a 500 properly (and logs the exception by default):

```scala
import cats.effect.{ExitCode, IO, IOApp}
import org.http4s.HttpRoutes
import org.http4s.blaze.server.BlazeServerBuilder

import scala.concurrent.ExecutionContext

object Y extends IOApp {
  implicit val ec: ExecutionContext = scala.concurrent.ExecutionContext.Implicits.global

  override def run(args: List[String]): IO[ExitCode] = {
    val routes2 = HttpRoutes.of[IO] { case _ =>
      throw new IllegalArgumentException("boom")
    }

    // starting the server
    BlazeServerBuilder[IO]
      .withExecutionContext(ec)
      .bindHttp(8080, "localhost")
      .withHttpApp(routes2.orNotFound)
      .resource
      .use { _ => IO.never }
      .as(ExitCode.Success)
  }
}
```

Something seems to be wrong with cats-interop exception handling.

Finally, there's the problem in tapir itself:

```scala
java.lang.IllegalArgumentException: None of the mappings defined in the one-of output: status code (418) {body as text/plain (UTF-8)}, is applicable to the value: fail. Verify that the type parameters to oneOf are correct, and that the oneOfVariants are exhaustive (that is, that they cover all possible cases).
	at sttp.tapir.server.interpreter.EncodeOutputs.applySingle(EncodeOutputs.scala:72)
```

which is due to the fact that you are using the same types for both `oneOf` base and variant. The discrimination is done on types only, hence the first branch is only ever tried. I'll see if I can extend that discrimination to include other fields as well.

**Comment by adamw** [comment]
@jwojnowski I looked if handling `.errorOutVariant` the way you tried to use it would work, but unfortunately that's not possible. This method creates a new `oneOf`, with two branches: one using the current output, and the second provided. The first one is used if the run-time type matches the current type of the output. If such a match is found, only that brnach is checked.

That's why in your test, as both branches where `String`s, only the first one was ever considered. As no applicable mappings were found there, an exception was thrown (although in your case it was suppressed by ZIO)

The docs where misleading, suggesting that appending variants actually happens, so I fixed this and hopefully the description is clearer now.

I've also added another method (https://github.com/softwaremill/tapir/pull/2438), with which you can prepend more specialised error out variants, leaving the current error out as a default. Maybe this would work for you (I don't know your exact use-case).

**Comment by adamw** [comment]
I'll assume that the updated scaladocs explain why this happens and allow avoiding the problem.

**Comment by adamw** [comment]
Let me know if `errorOutVariantPrepend` would work as expected or not. There's also always yet another possibility - defining the "base" endpoint as a method, parametrised with `OneOfVariant`s for errors. Then you have the additional flexibility :)
