### ISSUE TITLE
Add SSE checkbox in adopt a tapir ?

### ISSUE THREAD

**Issue by fmeriaux** [softwaremill/tapir#2510]
Hello!

Currently we are using an akka backend and we want to migrate to a new backend supported by Tapir.

I've been reading up and looking at the adopt a tapir tool to see my options.

Using Future Scala, it looks like the proposed choice is Netty. 
But according to the backend documentation, SSE would not be supported (unlike Http4s). 

Is it possible to consider SSE in the requirements to adopt a tapir?

Also, should we migrate our futures to cats/zio-effects to use Http4s or Netty can support SSE (they support websocket I guess so it's possible?)

**Comment by adamw** [comment]
You're right that SSE will only currently work with akka-http or http4s. At some point we'd like to add SSE support to other interpereters (such as Netty), but first we must add streaming support there (once this is done, SSE is easy :) ).

Using http4s is a bit more tricky, as you'd have to use another effect, such as `IO`, instead of `Future`. Not sure if this is an option for you.

**Comment by fmeriaux** [comment]
We will probably migrate to cats-effect but we would like to decouple the migrations as much as possible.

Thanks for your clarifications :)

**Comment by adamw** [comment]
Closing this as adding streaming to Netty is covered by other issues, and the feature set of adopt-tapir is closed (too many degrees of freedom would make it really hard to maintain)
