### ISSUE TITLE
[BUG] Case class not found with `mapInTo`

### ISSUE THREAD

**Issue by worekleszczy** [softwaremill/tapir#2540]
Tapir version: 1.1.3

Scala version: 2.13.8

**Describe the bug**

Compiling the following snippet:

```
object BuildRequest {
  final case class Input(
    token: Option[String],
    correlationId: Option[String]
  )

}
object Endpoints {


  val betBuild: Endpoint[Unit, BuildRequest.Input, Unit, Unit, Any] =
    endpoint.post
      .in("build")
      .in(cookie[Option[String]]("jwt"))
      .in(header[Option[String]]("X-Correlation-Id"))
      .mapInTo[BuildRequest.Input]

}
```

fails to compile with an error:
```
not found: value Input
      .mapInTo[BuildRequest.Input]
```

**How to reproduce?**

Compile the source code above 🙃

**Additional information**

Snippet could be made to compile by adding an import:
 ```
import BuildRequest.Input
```
and rewriting `mapInTo` to:
```
      .mapInTo[BuildRequest.Input]
```

But the experience I'm going for here is to have all **dto**s (e.g. Input, Output, Error type etc) for every endpoint specify in the individual object like `GetUser`, `CreateUser` etc and then have all endpoints definitions in one place for a particular domain.

**Comment by rafalambrozewicz** [comment]
Hi @worekleszczy ,

It looks like it is not possible to fix this problem reliably. Thankfully workaround that you have provided above i.e. to add an appropriate import, is available. Also, the bug mentioned above cannot be reproduced for Scala 3.

Below, I am going to describe the root cause of the problem and what have we tried to fix this as it might be useful if someone stumbles upon a similar problem in the future.

**What's the problem?**

During the macro expansion `myEndpoint.mapInTo[Wrapper.MyCaseClass]` gets converted to something like: 

```scala
myEndpoint.mapIn(((paramsTuple) => /* here => */MyCaseClass(paramsTuple) /* <= here */))(((t: MyCaseClass) => scala.TupleX(paramsTuple)))
```

Notice, that the constructor in the first function uses `MyCaseClass`, which is unknown at this scope. This results in `not found: value MyCaseClass` error. To fix this we could add an import so that `MyCaseClass` would become something known at this scope or change the macro so that the constructor would use `Wrapper.MyCaseClass` instead of `MyCaseClass`. 

**What could be done?**

Our bet bests were to use a fully qualified path for `CASE_CLASS` or get a "handle" on it differently:

```scala
def myMacro[CASE_CLASS: c.WeakTypeTag](c: blackbox.Context): c.Tree = {
  import c.universe._
  
  val t: Type = weakTypeOf[CASE_CLASS]
  
  // current solution
  val currentSolution: TermName = t.typeSymbol.asClass.asType.name.toTermName
  val caseClassConstructionWithCS: Tree = q"${currentSolution}/*needed params*/"
  
  // best bet #0: using full path
   val fullyQualifiedName: String = t.typeConstructor.toString // com.mypackage.myobject.Wrapper.MyCaseClass
   val caseClassConstructionWithFQN: Tree = q"${c.parse(fullyQualifiedName)}/*needed params*/"
   
  // best bet #1: building tree "manually"
  val constructorTreeBuildManually: Tree = Select(New(Ident(t.dealias.typeSymbol)), termNames.CONSTRUCTOR)
  val caseClassConstructionWithCTBM: Tree = q"${constructorTreeBuildManually}/*needed params*/"
  ...
}
```

and they do fix the provided problem but fail in other cases like:

```scala
class MyClass {

  object Wrapper {
    case class MyCaseClass(/*params*/)
  }
  
  myEndpoint.mapInTo[Wrapper.MyCaseClass]
}
```

or

```scala
def myFunction(): Unit = {
  object Wrapper {
    case class MyCaseClass(/*params*/)
  }

  myEndpoint.mapInTo[Wrapper.MyCaseClass]
}
```

**Comment by worekleszczy** [comment]
@rafalambrozewicz Thanks for looking into this 🙂 It's a little bit of a bummer that it cannot be solved, but it's a good thing that it's not affecting scala 3 - yet another reason to upgrade 🙃
