### ISSUE TITLE
Duplicate logging with http4s

### ISSUE THREAD

**Issue by kamilkloch** [softwaremill/tapir#2600]
When the http4s router combines multiples routes as follows: `Router[IO]("/" -> (routes1 <+> routes2))`
and tapir's server options are defined as follows:
```scala
    val serverOptions = Http4sServerOptions
      .customiseInterceptors[IO]
      .serverLog {
        Http4sServerOptions
          .defaultServerLog[IO]
          .copy(logWhenReceived = true)
          .doLogWhenReceived(msg => IO.println(msg))
      }
      .options
```
then `doLogWhenReceived` is invoked twice for a non-exisitng endpoint:
```
Request received: GET /non-exisitng
Request received: GET /non-exisitng
```

Complete example repository: https://github.com/kamilkloch/tapir-logging

**Comment by kamilkloch** [comment]
@adamw I updated the repo to include native http4s requesst logging. `GET hello` gives now the following:
```
Request received: GET /hello
Request received: GET /hello
11:47:37.668 [io-compute-blocker-5] INFO org.http4s.server.middleware.RequestLogger - HTTP/1.1 GET /hello
```
http4s middleware logs it once, tapir is logging it twice. So at least the task seems possible one digs deep enough into the middleware layer :)  Current state of duplicated logging is kind of show-stopper...

**Comment by adamw** [comment]
If the tapir interpreter is invoked multiple times for different sets of endpoints, than each interpreted result will run its own stack of interceptors.

The `Request received` log is logged (when enabled - can be disabled!) when tapir starts any processing of the request. It is possible to log information once the request is starting to get handled by a specific endpoint, after decoding the endpoint's inputs has completed successfully (so that we know that the endpoint "matches" the request). This can be done in a custom interceptor - but it won't be truthful as it won't include the time needed to actually decode the request. I don't think we are able to do anything above that in tapir.
