### ISSUE TITLE
Schema for class (not case class)

### ISSUE THREAD

**Issue by KarlHakanNordgren** [softwaremill/tapir#2874]
Hi

Let's say that I have the following class:

`class Klazz(a: String, b: Int)`

How do i write a schema for the above? The following does not work:

`implicit def klazzSchema = Schema.derived[Klazz]`

**Comment by adamw** [comment]
Indeed, automatic derivation works only for case classes.

You'd need to manually write the schema in such a case, e.g.:

```scala
import sttp.tapir.Schema.SName
import sttp.tapir.{FieldName, Schema, SchemaType}

object X extends App {
  class Klazz(val a: String, val b: Int)

  def klazzSchema = Schema(
    SchemaType.SProduct(
      List(
        SchemaType.SProductField[Klazz, String](
          FieldName("a"),
          Schema(SchemaType.SString()),
          k => Some(k.a)
        ),
        SchemaType.SProductField[Klazz, Int](
          FieldName("b"),
          Schema(SchemaType.SInteger()),
          k => Some(k.b)
        )
      )
    ),
    Some(SName("sttp.tapir.examples.X.Klazz"))
  )

  println(klazzSchema)
}
```

Note that I had to add `val`s to the class fields, so that they are accessible to `get` of the `SProductField`. This is neede for validaton - if there are no validation rules defined for the fields, these methods can return none, e.g. `k => None`
