### ISSUE TITLE
Server timeouts per endpoint

### ISSUE THREAD

**Issue by markusheilig** [softwaremill/tapir#3030]
Hi!

I would like to define server timeouts per endpoint.
In order to not stick to any specific server implementation I created an `EndpointInterceptor` which uses a `scheduledThreadPool` to detect timeouts.

Here the link to a gist, example is at the bottom: https://gist.github.com/markusheilig/6be48c908d42443fc3e623545da53e93

Would be happy to hear what you think about this and to get some feedback.
Thanks :-)

**Comment by adamw** [comment]
For a `Future`-based interpreter, I think this looks good :) That's what interceptors are for!

One minor improvement might be to use attributes instead of subclassing `Endpoint`. This would also allow you to specify the timeout at any stage of the endpoint's definition. E.g.:

```scala
// globally
case class Timeout(millis: Long)
val timeoutAttribute = AttributeKey[Timeout]

// endpoint definition
myEndpoint.attribute(timeoutAttribute, Timeout(1000L))

// interceptor
myEndpoint.attribute(timeoutAttribute): Option[Timeout]
```

Another thing is, do you need the `blocking` wrapper when invoking the downstream handler? Anything that is blocking should be already wrapped close to the actual blocking operation.

**Comment by markusheilig** [comment]
Thanks @adamw for your feedback, this was very valuable! 🙏 
I changed my solution according to your comments and also did some refactoring to simplify the code.
The latest revision is now revision 5 of [my gist.](https://gist.github.com/markusheilig/6be48c908d42443fc3e623545da53e93/revisions)
