### ISSUE TITLE
[BUG] `.oneOfVariant[Some.type]` catches all types

### ISSUE THREAD

**Issue by bjornakr** [softwaremill/tapir#3122]
Tapir version: 1.7.1

Scala version: 3.3.0

**Describe the bug**

*Disclaimer:* I am not sure if this is a problem with Tapir, it might be how types work in Scala.

When using an enum like this:
```scala
enum MyError {
  case A
  case B
}
```
with error handling like this:

```scala
.errorOut(
  oneOf[MyError](
    oneOfVariant[MyError.A.type](
      StatusCode.BadRequest,
      emptyOutputAs(MyError.A)
    ),
    oneOfVariant[MyError.B.type](
      StatusCode.UnprocessableEntity,
      emptyOutputAs(MyError.B)
    )
  )
)
```

if I try to produce an error of type B, it is caught by the handler for type A. However, if I define my error like this:

```scala
enum MyError {
  case A()
  case B()
}

oneOfVariant[MyError.A](  // lose the '.type'
  StatusCode.BadRequest,
  emptyOutputAs(MyError.A)
)
```

...it works as intended. Like I said, unsure if this is how types work, but I thought those would be equivalent.

**How to reproduce?**

Try it out here: https://scastie.scala-lang.org/gCL8Akg9TPyON86wsGBfxA

**Comment by adamw** [comment]
That's because if an enum has only parameterless cases (as in your example), the compiler creates an encoding where each case is a *value* of class *MyError*, not a proper subtype. So in this case `MyError.A.type` is a singleton type. However, `oneOfVariant` uses a `ClassTag` to determine if the passed in value is matching at run-time. And both `A` and `B` are of class `MyError` - hence the invalid behavior.

In the second example, `A()` is a proper class, and a subclass of `MyError`, hence the type-test works.

To fix this, you can use e.g. `oneOfVariantExactMatcher`:

```scala
.errorOut(
  oneOf[MyError](
    oneOfVariantExactMatcher(
      StatusCode.BadRequest,
      emptyOutputAs(MyError.A)
    )(MyError.A),
    oneOfVariantExactMatcher(
      StatusCode.UnprocessableEntity,
      emptyOutputAs(MyError.B)
    )(MyError.B)
  )
)
```
