### ISSUE TITLE
BigDecimal representation mismatch between tapir and circe

### ISSUE THREAD

**Issue by guersam** [softwaremill/tapir#321]
Tapir assumes a `BigDecimal` to be encoded to a string, whereas Circe encodes it to a number. This mismatch results in incorrect OpenAPI documentation.

tapir:
```scala
  implicit val schemaForBigDecimal: Schema[BigDecimal] = Schema(SString)
  implicit val schemaForJBigDecimal: Schema[JBigDecimal] = Schema(SString)
```

circe:
```scala
@ import $ivy.`io.circe::circe-core:0.12.3` 
import $ivy.$ 

@ io.circe.Encoder[BigDecimal].apply(BigDecimal(3)) 
res1: io.circe.Json = JNumber(JsonBigDecimal(3))
```

**Comment by guersam** [comment]
Just found out a former discussion about it in #99.

**Comment by gbastkowski** [comment]
I also just came across this issue.
I do feel that a "correct" default representation of BigDecimal in JSON is String.
But as circe's default is to encode BigDecimal as a Number, tapir should stick to that.

The current behavior causes inconsistencies between sample requests and the schema documentation (fields are documented as being of type string, while the sample request shows a JSON-Number).

**Comment by geirolz** [comment]
Any update ? This is very frustrating, at documentation level creates a lot of confusion

**Comment by adamw** [comment]
@geirolz Well I'm not convinced that we should follow suite as to what circe defines - it's the most popular json integration, but not the only one.

And you can always override the schema by providing a higher-priority implicit. E.g. if you use the "my tapir" approach, of creating a custom object which brings together all of the tapir traits, you can define your own schema there (https://tapir.softwaremill.com/en/latest/mytapir.html). Alternatively, you can override circe's codecs for `BigDecimal`s, so that they are serialised as strings.

**Comment by geirolz** [comment]
@adamw You're perfectly right, tapir core should be as generic as possible. But since there is the module dedicated for Circe what do you think to add this schema override there? This should resolve this mismatch for all Circe users

**Comment by adamw** [comment]
@geirolz hm why not ... see https://github.com/softwaremill/tapir/pull/1405
