### ISSUE TITLE
multipart upload request, file part to be streamed (http4s)

### ISSUE THREAD

**Issue by twr143** [softwaremill/tapir#364]
There is not clear how to upload multipart requests with one part as a [possibly large] file. 
```scala 
sttp.tapir.Tapir#multipartBody
```
accepts a case class like 
```scala
case class FormWithFile(title: String, file: ? )
``` 
What is supposed to be the type of file field? How to derive its codec? After that, how to process file body as a streaming content? So far what I found for https4s and IO is the following handing:
```scala
case req @ POST -> Root / "post" => {
req.decode[Multipart[IO]] { m => {
      m.parts.find(_.name == Some("dataFile")) match {
        case None => BadRequest(s"Not file")
        case Some(part) => for {
          contents <- part.body.through(utf8Decode).runFoldMonoid
          response <- Ok(s"""Multipart Data\nParts:${m.parts.length}
                            |File contents: ${contents}""".stripMargin)
        } yield response
      }
    }
   }
  }
 }
```

**Comment by adamw** [comment]
The problem with parsing multipart requests and streaming is that to decode a multipart request in full - and hence to know what the parts are - you need to somehow buffer the whole body anyway.

So even if you get a stream for one of the parts, that stream won't read directly from the network, but the request will have to be buffered (either in-memory or on disk), and the stream will then read from that buffer.

If you look at http4s's code for handling multipart, it's buffering in-memory for small parts, and then switching at some point to buffering into a file.

That's why I would simply do `case class FormWithFile(title: String, file: File)`. This will be a temporary file created through the method in `ServerOption`s. Then, if you need to, you can stream this file, or just pass it around.

**Comment by twr143** [comment]
It really works as you say. Closing this.
