### ISSUE TITLE
Partial<> from javascript analog

### ISSUE THREAD

**Issue by boryaferz** [softwaremill/tapir#3844]
Is it possible to do something similar to Partial<> from javascript when describing endpoint with patch method, for example?
Now I do this but don't like:
 case class Course_[F[_]](
      title: F[String],
      description: F[String],
      price: F[Long]
  )
  type Course = Course_[Id]
  type CoursePatch = Course_[Option]

**Comment by adamw** [comment]
I'm not aware of any tapir-specific patterns, so this might be a more general-Scala question. On first attempt, I think I would model it as you did. After all, you need to somehow express the optionality of each field in types. 

The problem then is, what about optional fields? That is situations where you end up with `Option[Option[X]]` in the patch. Probably the json decoder would need to handle this appropriately when seeing a missing vs. `null` field?

**Comment by boryaferz** [comment]
Now i use jsonBodyWithRaw and parse json again for filter fake nulls..

**Comment by boryaferz** [comment]
found a good idea https://github.com/pathikrit/metarest

**Comment by adamw** [comment]
@boryaferz yeah macros could work, though it might be problematic in IDEs.

I don't know which json parser you are using, but I think it should be possible to configure it to properly handle nested options, so that you don't have to do any hand-parsing. `jsonBody` just takes the json encoders/decoders that are in scope. But that's more of a question regarding the json library.

**Comment by boryaferz** [comment]
Thanks
