### ISSUE TITLE
Implement multipart body support in sttp stub

### ISSUE THREAD

**Issue by urieli** [softwaremill/tapir#3902]
Multipart support was never added to the stub: https://github.com/softwaremill/tapir/blob/abeb5d72e4e7a16c4da3830a59eb58862dfda69b/server/sttp-stub-server/src/main/scala/sttp/tapir/server/stub/SttpRequestBody.scala#L49

This makes it impossible to test endpoints with multipart bodies.

_Originally posted by @adamw in https://github.com/softwaremill/tapir/issues/3895#issuecomment-2208480834_

**Comment by asr2003** [comment]
Hey @adamw! I’d love to take a crack at adding multipart body support to the sttp stub. Here’s what I’m thinking for the approach:

Right now, the code throws an exception for MultipartBody. My idea is to properly parse multipart bodies instead of the exception. I will iterate over the parts, handling text and files and convert them into something Tapir can understand like `RawBodyType.MultipartBody.Part`. Once we can parse the multipart, I think we can update `toRaw` to return the proper raw value. So when the body type is `RawBodyType.MultipartBody`, it will grab the parsed parts and wrap them in `RawValue[Seq[RawBodyType.MultipartBody.Part]]`

I will also create some test cases that include multipart bodies with both text and file parts.

Does this sound good? I will get started and push a PR soon if all looks good to you! With this,
/attempt #3902

**Comment by adamw** [comment]
@asr2003 Hey, great to see your interest in the issue! :) I'm not sure doing full multipart serialisation & parsing will be necessary (unless I'm missing something), but maybe it will be enough to remain on a higher level. I think a great start would be to create (failing) tests which would demonstrate how people might use the feature: either directly via sttp-client, or by interpreting the endpoint as a client. This should probably be an extension to the existing testsuite. Then we might work out what exactly is missing to make this work.

**Comment by adamw** [comment]
As we are getting first PRs for the bounties, I've published our ["How to prepare a good PR" guide](https://softwaremill.community/t/how-to-prepare-a-good-pr-to-a-library/448). I should have probably done this right away, sorry! :)
