### ISSUE TITLE
support for openapi specification extensions

### ISSUE THREAD

**Issue by gustavofranke** [softwaremill/tapir#519]
I’m interested in adopting Tapir in order to describe an api to generate its swagger document.
But in order to do so, I need to add aws api gateway swagger extensions into the generated file.

I haven't found an existing mechanism for generating these api gateway extensions.

Specifically to aws, these are the extensions I’m referring to: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions.html, but in general open api, supports them on the root level of the API spec and in the following places (as per https://swagger.io/docs/specification/openapi-extensions/):
* info section
* paths section, individual paths and operations
* operation parameters
* responses
* tags
* security schemes

Thanks!!

**Comment by adamw** [comment]
The step here would be to take the existing open api model (https://github.com/softwaremill/tapir/blob/master/openapi/openapi-model/src/main/scala/sttp/tapir/openapi/OpenAPI.scala) and extend it so that it would support arbitrary extensions. Next, add circe encoders/decoders which could deal with such freeform data. 

As for applying the metadata - we would either think of a "payload" attribute of endpoints/endpoint inputs/outputs, or modifying the resulting `OpenAPI` object using e.g. quicklens.
