### ISSUE TITLE
[BUG] Endpoints with equal paths&methods are silently ignored for OpenAPI

### ISSUE THREAD

**Issue by kubukoz** [softwaremill/tapir#635]
Tapir version: 0.16.1

Scala version: 2.13.2

**Describe the bug**

What is the problem?

The OpenAPI support merges multiple endpoints with the same HTTP method & path into the first endpoint, silently ignoring the second one:

```scala
package example

object HelloEndpoints {
  import sttp.tapir._
  import sttp.tapir.json.circe._

  val base = infallibleEndpoint.in("examples")

  val one = base.get.in(query[String]("foo"))
  val two = base.get.in(query[String]("bar"))
}


object Hello extends App {
  import sttp.tapir.docs.openapi._
  import sttp.tapir.openapi.circe.yaml._

  println(
    List(HelloEndpoints.one, HelloEndpoints.two)
      .toOpenAPI("Title", "version")
      .toYaml
  )
}

```

Results in this YAML:

```yaml
openapi: 3.0.1
info:
  title: Title
  version: version
paths:
  /examples:
    get:
      operationId: getExamples
      parameters:
      - name: foo
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
```

**How to reproduce?**

Run this: https://github.com/kubukoz/tapir-openapi-repro (or just generate YAML from the snippet above)

**Comment by kubukoz** [comment]
About possible solutions - I've thought about this in the past for the general case (not just OpenAPI, but servers as well): Given a list of endpoints, Tapir should be able to recognize the ones that overlap (e.g. `/foo/:{id(string)}` and `/foo/bar`) and log an error/warning if any are unreachable at the time of building the router / documentation.

**Comment by adamw** [comment]
For OpenAPI, I think we should throw an exception - or return an `Either` - as silently dropping endpoints isn't nice. Better to be upfront about it :)

For servers, it's more complex. You can have your own `DecodeFailureHandler`, which in case of e.g. a missing query parameter, tries the next endpoint (returns `NoMatch`), instead of providing a 401 response. The handler is arbitrary code, so we cannot know if two endpoints overlap or not. We can't even tell if they are identical (well, unless the instances are reference-identical, but that's rather unintersting ;-) )

**Comment by adamw** [comment]
There's a utility to find shadowed endpoints - which could detect cases like this: https://tapir.softwaremill.com/en/latest/testing.html#shadowed-endpoints

Though the openapi interepreter will continue silently dropping for now

**Comment by adamw** [comment]
I don't think we'll be able to come up with a better solution than the endpoint verifier, but please reopen if there are new ideas
