### ISSUE TITLE
Dotty / Scala 3 support

### ISSUE THREAD

**Issue by hamnis** [softwaremill/tapir#852]
Any plans for supporting Dotty / Scala 3 ?

**Comment by adamw** [comment]
Definitely! Some work will need to be done to migrate the macros. However, if/once there's a Magnolia release for Scala3, this will be much easier.

On the server side, we depend on akka-http/http4s. Otherwise migration shouldn't be a problem.

On the client side, sttp-client is already available for Dotty.

**Comment by heksesang** [comment]
Magnolia is hopefully being released for Scala 3 in a couple of days, with that in place there should be nothing to prevent a migration to Scala 3. It would be nice if there could be a Scala 3 release of tapir in not too long (is a few weeks too optimistic?).

**Comment by adamw** [comment]
See ongoing work in https://github.com/softwaremill/tapir/pull/1204

**Comment by adamw** [comment]
And more ongoing work in https://github.com/softwaremill/tapir/pull/1315

**Comment by DenisNovac** [comment]
Hi. I see a version 0.18.0-M17 for Scala 3 in Maven. Is it ready to try?

**Comment by adamw** [comment]
@DenisNovac yes, please do! By the way, closing the issue :)

**Comment by Swoorup** [comment]
Is there a Scala3 replacement for tapir-sttp-stub-server?

**Comment by adamw** [comment]
@Swoorup it simply wasn't enabled :) Fixed in https://github.com/softwaremill/tapir/commit/54e3009942fcf04fffc1bdea5fff9de80dcd3530, will be there in the next release
