### ISSUE TITLE
`asIterable` always creates optional properties

### ISSUE THREAD

**Issue by oscar-broman** [softwaremill/tapir#993]
Why does the automatic schema generation make `arr` optional in this example:
```
case class Test(arr: Seq[Double])
```

There's a big difference between an empty array and not providing an array at all!

**Comment by adamw** [comment]
There is? I would say both are equivalent to an empty array :)

And having an empty array means that the field is optional, no?

**Comment by oscar-broman** [comment]
They are as different as `Option[Seq[Double]]` is different from `Seq[Double]`. 

If someone calls the endpoint and fails to provide an array, surely that shouldn't be interpreted as an empty array? That's just as bad as defaulting an `Int` to `0` or `String` to `""`.

**Comment by Y-Less** [comment]
That entirely misses the point.  An Seq with elements shouldn't be optional by default.  Even if you think an empty Seq is equivalent to no Seq, there's no way you can think a non-empty Seq is equivalent to no Seq.  If they have to provide some items, currently the schema does nothing to enforce that, regardless of whether you think 0 or 1 elements should be the minimum.  Of course, if the field is then non-optional, but no data exists, then it absolutely follows that an empty (but explicitly provided) Seq is distinct from a missing Seq.

**Comment by adamw** [comment]
I would say that an API which differentiates between an empty array and just not providing the array is poorly designed and surprising to developers, but that's of course just my subjective opinion. 

And it's something completely different from defaulting a string field to `""`. Rather, I would say that a `null` field and omitting the field is equivalent to a missing value (`None` in Scala). Some for strings and arrays.

If you require non-empty arrays, it might be best to use a dedicated data type, such as `NonEmptyList` - the schema for that type (after including the cats integration) is non-optional.

You can also override the default schema for iterables by defining your own implicit e.g. in your [custom-tapir object](https://tapir.softwaremill.com/en/latest/mytapir.html?highlight=MyTapir#creating-your-own-tapir). This should have a higher precedence than the built-in one.

**Comment by oscar-broman** [comment]
For example, let's say we are modeling a soccer game, and we have an endpoint to give some metrics about a match. Most of the time we know the sequence of goals scored, e.g. `Seq(Home, Away, Away)` meaning the home team scored first then the away team twice.
However, in some cases the sequence of goals is unknown, and we need to distinguish that from the game ending 0-0 (which is represented as an empty array if the score is known). In this case, there's a clear difference between providing an empty array and not providing an array at all.

Your reasoning about strings is contradictory to your reasoning about arrays. The two are completely analogous, since a string is just an array of characters!

**Comment by adamw** [comment]
Sure, you could model an API as you described, I would do it differently - e.g. by introducing a `goalsUnknown` flag. I think that would be more readable for developers working with that API. Yes we could compress that information and represent it with a single array field, but compression has its downsides - it's harder to comprehend. But, that's really a whole other topic, about API design :) 

I think you can quite easily achieve that using tapir, if you wish.

> Your reasoning about strings is contradictory to your reasoning about arrays. The two are completely analogous, since a string is just an array of characters!

Well but we don't usually work with strings as if they were character arrays, at least in JSON, as we have a dedicated type for that, with different expectations. We treat string values as indivisible wholes, rather than as collections with 0 to n elements

**Comment by oscar-broman** [comment]
My example was simplified, but having multiple arrays like this, requiring accompanying flags, would just make everything grow in complexity for no good reason. If I fetch the data from a database and send that to a computation endpoint, it wouldn't make sense having to decorate every piece of missing information as explicitly missing - I'd prefer using `Option` for that!

The fact that `Option[Seq[T]]` is equivalent to `Seq[T]` in tAPIr seems like a bad design decision. I understand, however, that it will be too late for you to change anything at this point so I'll resort to overriding the `Iterable` conversion in a package object.

It would, however, be nice if this could be configured somehow with an implicit `Configuration` object or something (similar to Circe's semiautomatic derivation).

**Comment by adamw** [comment]
Let's leave this issue open. We'll see if others would like to see this changed too - I might be wrong or have a different opinion than most ;). 

Or if not change, make it configurable somehow, though `Configuration` is for generic derivation, and here we've got normal implicit resolution. So this would have to be another type.

**Comment by oscar-broman** [comment]
I'm still having issues with my custom codec, since there isn't really a way to override the default ones. Ambiguous implicit.

Perhaps the implicits in `Schema` could be moved to `LowPrioritySchema` so they wouldn't clash with custom ones that override them? Or is there a reason they're not there?

**Comment by adamw** [comment]
@oscar-broman ah ... how do you define your implicits? in an object & then imported into scope?

I thought improted implicits have higher priority than from companion objects, but I might be wrong of course. If putting them in `LowPrioritySchema` lowers their priorty then I don't have anything against. We'd just need to put the current `derivedSchema` into an even lower level :)

**Comment by yurique** [comment]
Some copy paste from the gitter discussion. 

If I have a `POST` body specified as a list of something:

```scala
      .in(jsonBody[List[MyData])
```

in the generated openapi spec it is marked as optional:

```
"requestBody": {
  "content": {
    "application/json": {
      "schema": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/MyData"
        }
      }
    }
  },
  "required": false
},
```

then the openapi generator for typescript, for example, generates this the client that has an optional body as well:

```typescript
export interface MyEndpointRequest {
    myEndpointReq?: Array<MyData>;
}
```

But if you try to actually send a request with `undefined` (empty) body, you get an error from circe (in my case at least, I'm using circe+http4s):

```
"Invalid value for: body (DecodingFailure at : C[A])"
```

**Comment by adamw** [comment]
Given that there's quite a lot of misunderstandings given the current state, I've tried switching this default in code, so that collection-valued schemas are marked as required, not optional. However, before we overlooked the fact that whether such a field should be considered optional or not is, in addition to other aspects, contextual.

For example, a query parameter such as `query[List[String]]("x")` is quite obviously optional; same for headers. A CSV body mapped as a `List[String]` is also optional.

Things *might* be considered different in JSON, as JSON has `null`s and fields might be absent. But then again for XML, a list of child elements would be considered optional.

Unfortunately schema derivation isn't context-dependent, that is, we don't know if we're deriving a schema for a value that will be serialised to JSON, XML or a string, so I don't think we can take into account the specifics of the JSON format. Hence, (once again :) ) I'd keep the behavior as-is, with the following work-arounds, if another behavior is needed:

* use `NonEmptyList` or similar if the collection should be non-empty
* define a local implicit `implicit def schemaForIterable[T: Schema, C[X] <: Iterable[X]]: Schema[C[T]] = implicitly[Schema[T]].asIterable[C].copy(isOptional = false)` when deriving the schema for a json field, e.g. in a block in which `jsonBody` is called
* [customise](https://tapir.softwaremill.com/en/latest/endpoint/schemas.html#customising-derived-schemas) the derived schemas

Closing the issue for now, if there would be any other ideas on this subject, I'll re-open.

**Comment by worekleszczy** [comment]
@adamw what do you think about adding additional annotation `required` or `isDefault(default: Boolean)` [here](https://tapir.softwaremill.com/en/latest/endpoint/schemas.html#using-annotations)? I think this would allow to override this behaviour quite easily on a single field basis 🙃

**Comment by adamw** [comment]
@worekleszczy Hm maybe ... my worry would be that `required` would be misleading and people would try to use it when they don't need to. So if we include this, we would need good docs.

But are `required` and `isDefault` alternatives? What would `isDefault` do when applied to a field - how would it modify the schema?

**Comment by szagi3891** [comment]
Generating specifications from code is not the place to create hidden assumptions. If a field is required, it must be required in the specification. The current behaviour of how this generator works should be changed. So a request to the authors of this library to change this behaviour to normal / correct / without any hidden assumptions.

**Comment by adamw** [comment]
@szagi3891 What do you mean by hidden assumptions?

There are good reasons for the current design (see https://github.com/softwaremill/tapir/issues/993#issuecomment-912588917). Do you have a proposal on how to solve this differently?

**Comment by adamw** [comment]
@oscar-broman @szagi3891 XML is just the chery on top; bodies other than JSON (e.g. the CSV mentioned) are rarely used. The real problem is e.g. with query parameters or header values, as described in the comment. Given current design of Tapir schemas & codecs, I do not see a way to fix this - but of course, I might be wrong - in that case, please propose another solution.

Also, I do understand that you passionately oppose the current design, but your comments seem quite aggressive. Not sure if this was your intention, but please let's try to keep this discussion technical. Believe me or not, I'm not trying to make your life miserable ;).

**Comment by adamw** [comment]
> I understand where you're coming from and that there are practical reasons making it hard to uphold good principles. In this instance, one possible suggestion in that case would then be that the more forgiving behavior should be moved towards the areas where it is necessary.

Well, as I wrote earlier, API design is a completely different topic. Tapir should support whatever people want to model (well, almost), regardless of what I or somebody else considers "good design" :)

> So let's say somebody has a schema that might fail from a lack of value where one was expected, perhaps this failure could be recovered from in case the schema was used to decode information given via XML or query parameters.

But then sometimes query parameters are *really* required. So we would need to have "kind-of-required" schemas, and "I'm sure it's required" schemas. Which brings us back to the same problem ;)

I do understand the problem, but for sure we are not going to change the defaults at this point in tapir's lifecycle (that is, in the 1.x version). In 2.x, for which there are no plans, we might consider a change, but we still have to take into account the problems I mentioned earlier.

Maybe some kind of configuration would work? Or saying that during derivation, only top-level collections are marked optional, but any nested collection-typed fields are required? Not sure if that wouldn't be surprising, though.

**Comment by nimatrueway** [comment]
I used the following workaround for the time being in my project

```scala
import sttp.tapir.Schema.annotations.customise

final case class CaseClass(
  @customise(required)
  requiredList: Seq[CaseClass2],
  requiredString: String
)

object CaseClass {
  implicit val schema: Schema[CaseClass]   = Schema.derived[CaseClass]

  val required: Schema[_] => Schema[_] =
    ((s: Schema[Any]) => s.copy(isOptional = false))
      .asInstanceOf[Schema[_] => Schema[_]]
}
```

**Comment by theqp** [comment]
@nimatrueway `required` can be shortened to `def required[T](s: Schema[T]) = s.copy(isOptional = false)`

**Comment by nimatrueway** [comment]
> @nimatrueway `required` can be shortened to `def required[T](s: Schema[T]) = s.copy(isOptional = false)`

If I remember correctly, Scala 2.12.x can not deal with `[_]` as easily so I had to resort to that hack
